# üìò Notebook 01 : Contexte et prise en main des donn√©es

# 1. üß† Contexte du projet

Ce projet de Data Science est r√©alis√© dans le cadre d'une mission pour une entreprise d‚Äôassurance. L‚Äôentreprise souhaite savoir quels clients sont susceptibles de souscrire un contrat d‚Äôassurance v√©hicule cette ann√©e, √† partir de donn√©es clients issues de l‚Äôann√©e pr√©c√©dente.

Le r√¥le du Data Scientist est de construire un mod√®le pr√©dictif fiable et interpr√©table pour :

- Aider √† la prise de d√©cision strat√©gique (marketing, communication cibl√©e),

- Optimiser l‚Äôallocation des ressources commerciales,

- Prendre en compte les contraintes op√©rationnelles (compr√©hension m√©tier, explicabilit√©, performance, etc.).

# 2. üéØ Objectif et probl√©matique
Il s‚Äôagit d‚Äôun probl√®me de classification binaire supervis√©e, o√π l‚Äôon cherche √† pr√©dire :

üìå Est-ce qu‚Äôun client va souscrire (Response = 1) ou non (Response = 0) √† un contrat d‚Äôassurance v√©hicule ?

- Variable cible : Response

- Variables explicatives : toutes les autres colonnes (Age, Gender, Driving_Licence, etc.)

Le mod√®le devra :

- √™tre capable de g√©n√©raliser √† de nouveaux clients,

- g√©rer un √©ventuel d√©s√©quilibre de classes,

- fournir des indicateurs clairs pour les √©quipes m√©tiers.

# 3. üìÇChargement des donn√©es

In [14]:
# Importation de la librairie pandas
import pandas as pd

# Lecture du fichier CSV
df = pd.read_csv('base.csv')

# Dimensions du dataset
print('üìê Dimension de la base :', df.shape, '\n')

# Liste des colonnes
print('üßæ Liste des variables :')
print(df.columns)

# Aper√ßu des 10 premi√®res lignes
df.head(10)

üìê Dimension de la base : (381109, 13)

üßæ Liste des variables :
Index(['id', 'Gender', 'Age', 'Driving_License', 'Region_Code',
       'Previously_Insured', 'Vehicle_Damage', 'Annual_Premium',
       'Policy_Sales_Channel', 'Vintage', 'Response', 'Vehicle_Date',
       'Signature_Date'],
      dtype='object')

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response,Vehicle_Date,Signature_Date
0,1,NaN,44,1,28,0,1,40454,26.0,217,1,1411164000,1.550099e+12
1,2,0.0,76,1,3,0,0,33536,26.0,183,0,1488841200,NaN
2,3,0.0,47,1,28,0,1,38294,26.0,27,1,1459202400,1.570486e+12
3,4,0.0,21,1,11,1,0,28619,152.0,203,0,1515884400,NaN
4,5,1.0,29,1,41,1,0,27496,152.0,39,0,1528754400,NaN
5,6,1.0,24,1,33,0,1,2630,160.0,176,0,1526594400,NaN
6,7,0.0,23,1,11,0,1,23367,152.0,249,0,1537999200,NaN
7,8,1.0,56,1,28,0,1,32031,26.0,72,1,1504562400,1.558735e+12
8,9,1.0,24,1,3,1,0,27619,152.0,28,0,1517958000,NaN
9,10,1.0,32,1,6,1,0,28771,152.0,80,0,1515970800,NaN

# 4. üîç Description des variables

Voici les variables fournies dans la base `base.csv` :

- `id` : identifiant client
- `Gender` : 0 = homme, 1 = femme
- `Age` : √¢ge du client
- `Driving_Licence` : 1 = a le permis, 0 sinon
- `Region_Code` : code de la r√©gion
- `Previously_Insured` : 0 = pas encore assur√©, 1 = d√©j√† assur√©
- `Vehicle_Date` : date d'acquisition du v√©hicule
- `Vehicle_Damage` : 1 = v√©hicule d√©j√† endommag√©, 0 sinon
- `Annual_Premium` : prime annuelle en euros
- `Policy_Sales_Channel` : canal de vente anonymis√©
- `Vintage` : anciennet√© client en jours
- `Signature_Date` : date de signature du contrat
- `Response` : variable cible (0 = pas int√©ress√©, 1 = int√©ress√©)

# 5. ‚úÇÔ∏è S√©paration des variables X (features) et y (target)

In [16]:
# S√©paration des variables explicatives et de la cible
X = df.drop("Response", axis=1)
y = df["Response"]

# 6. üß™ S√©paration des jeux d'entra√Ænement et de test

In [17]:
from sklearn.model_selection import train_test_split

# S√©paration en train/test avec stratification
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.25,
                                                    stratify=y,
                                                    random_state=42)

# Affichage des dimensions
print("üß™ Dimensions des ensembles :")
print("Train :", X_train.shape, y_train.shape)
print("Test  :", X_test.shape, y_test.shape)

üß™ Dimensions des ensembles :
Train : (285831, 12) (285831,)
Test  : (95278, 12) (95278,)

# 7. üìä R√©partition des classes (variable cible)

In [18]:
# R√©partition des classes dans la variable cible
print("üìä R√©partition des classes dans y (variable cible) :")
print(y.value_counts(normalize=True))

üìä R√©partition des classes dans y (variable cible) :
Response
0    0.877437
1    0.122563
Name: proportion, dtype: float64

‚ö†Ô∏è Commentaire :
On observe un d√©s√©quilibre des classes : la majorit√© des clients ne souscrivent pas (classe 0).

Cela implique que la simple accuracy n‚Äôest pas suffisante comme m√©trique.
On utilisera aussi :

- le F1-score,

- le rappel (recall),

- ou la matrice de confusion.